config/routes.rb
Rails.application.routes.draw do

  get 'maps/index'

  root 'locations#index'

   post 'locations/create'

end

app/models/location.rb
class Location < ActiveRecord::Base
  def to_google_map
    {:latlng => [self.latitude, self.longitude]}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
  end

  def create
    ip = request.remote_ip
    geo = request.location

    location = Location.create(longitude: geo.longitude, latitude: geo.latitude,
                               country: geo.country, city: geo.city, ip: ip)

    redirect_to controller: :maps, action: index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happy</title>


  <style media="all">
    html, body{height:100%; text-align:center;}
    #outer{
      min-height:100%;
    }

    * html #outer{height:100%;} /* for IE 6, if you care */

    body, p { margin:0; padding:0}

  </style>

  <%= stylesheet_link_tag "application" %>


  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->

  <!--
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
 <link href="../../../../manifestinteractive-jqvmap-db5f009/dist/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />
   <script src="../../../../manifestinteractive-jqvmap-db5f009/dist/jquery.vmap.js" type="text/javascript"></script>
   <script src="../../../../manifestinteractive-jqvmap-db5f009/dist/maps/jquery.vmap.world.js" type="text/javascript"></script>
 -->

  <!--link href="../../assets/jqvmap.css" media="screen" rel="stylesheet" type="text/css" /-->

  <!--script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script-->
  <!--<script src="../../assets/jquery.vmap.js" type="text/javascript"></script>-->
  <!--<script src="../../assets/jquery.vmap.min.js" type="text/javascript"></script>-->
  <!--script src="../../assets/world.js" type="text/javascript"></script-->
  <!--<script src="../../assets/jquery.vmap.world.js" type="text/javascript"></script>-->
  <%= javascript_include_tag "application" %>
  <!--script>
    jQuery(document).ready(function () {
//      jQuery('#vmap').vectorMap({
//        map: 'world_en',
//        backgroundColor: '#333333',
//        color: '#ffffff',
//        hoverOpacity: 0.7,
//        selectedColor: '#666666',
//        enableZoom: true,
//        showTooltip: true,
//        scaleColors: ['#C8EEFF', '#006491'],
//        values: sample_data,
//        normalizeFunction: 'polynomial'
//      });
      jQuery('#vmap').vectorMap({ map: 'world_en' });
    });
  </script-->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/create.html.erb
<h1>Thanks!</h1>

app/views/locations/index.html.erb
<%= form_tag locations_create_path do %>
  <h1> Click smiley to Share your happiness!</h1>
   <div>
    <%= image_submit_tag 'Smiley.svg.png' %>
  </div>
<% end %>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/maps/index.html.erb
<h1>Maps#index</h1>
<p>Find me in app/views/maps/index.html.erb</p>

<!--div align="center" id="vmap" style="margin-right: auto; margin-left: auto; width: 800px; height: 400px; "></div-->
<div align="center" id="vmap" style="margin-right: 0; margin-left: 0; width: 100%; height: 500px; ">
<%=
  map(:center => {
      :latlng => [0, 174.7633],
      :zoom => 1,

  },
      :markers => Location.all.map{|location| location.to_google_map}
  )
%>

<ul>
  <%- Location.group(:country).count.each do |country, count| %>
  <li><%= country %>: <%= count %></li>
  <%- end %>
</ul>

<ul>
  <%- Location.all.each do |l| %>
    <%= l.latitude %>
  <%- end %>
</ul>
</div>